services:
  db:
    image: supabase/postgres:latest
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_URL}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${SPRING_DATASOURCE_USERNAME}
      - config.support_escapes=true
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"