server:
  port: 8080
spring:
  application:
    name: TableMaster API
  mail:
    port: ${MAIL_PORT:1025}
    host: ${MAIL_HOST:localhost}
    username: ${MAIL_USERNAME:luckyartem901@gmail.com}
    password: ${MAIL_PASSWORD:svmo utjz ekaf wqrq}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    jwt:
      secret-key: ${JWT_SECRET:hM9+XZfbJvGf/+nzwQl7q3fZnI2lhcwJmJI4O0KyQic/WFSpLndWqnRiGso7aVR08tnVJdfSaMRGrr+YyfMj+A==}
      expiration-time: 1h
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:E4dSR@FNT95W6#2}
    username: ${SPRING_DATASOURCE_USERNAME:postgres.teefqdmmynqovripovee}
  data:
    jdbc:
      dialect: postgresql
    redis:
      port: 6379
  cache:
    type: redis
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:E4dSR@FNT95W6#2}
    user: ${SPRING_DATASOURCE_USERNAME:postgres.teefqdmmynqovripovee}
logging:
  level:
    org:
      springframework:
        security: TRACE
        web: TRACE
        http: TRACE