server:
  port: 8080
spring:
  application:
    name: TableMaster API
  mail:
    port: ${MAIL_PORT}
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration-time: 3600000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${SPRING_DATASOURCE_USERNAME}
  data:
    jdbc:
      dialect: postgresql
    redis:
      port: 6379
  cache:
    type: redis
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
logging:
  level:
    org:
      springframework:
        security: TRACE
        web: TRACE
        http: TRACE