CREATE SEQUENCE IF NOT EXISTS dishes_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS ingredients_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS reservations_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS restaurant_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS restaurant_reviews_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS tables_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS tags_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE dishes
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          TEXT,
    restaurant_id BIGINT,
    price         numeric(6, 2),
    CONSTRAINT dishes_pkey PRIMARY KEY (id)
);

CREATE TABLE dishes_ingredients
(
    ingredient_id BIGINT NOT NULL,
    dish_id       BIGINT NOT NULL,
    quantity      numeric(6, 2),
    CONSTRAINT dishes_ingredients_pkey PRIMARY KEY (ingredient_id, dish_id)
);

CREATE TABLE ingredients
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     TEXT,
    quantity INTEGER,
    unit     VARCHAR(30),
    CONSTRAINT ingredients_pkey PRIMARY KEY (id)
);

CREATE TABLE reservations
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                BIGINT,
    table_id               BIGINT,
    restaurant_id          BIGINT,
    reservation_time_end   TIMESTAMP WITHOUT TIME ZONE,
    reservation_time_start TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT reservations_pkey PRIMARY KEY (id)
);

CREATE TABLE restaurant
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(100),
    description      TEXT,
    location         TEXT,
    rating           numeric(3, 1),
    count_of_reviews INTEGER,
    work_time_open   time WITHOUT TIME ZONE,
    work_time_closed time WITHOUT TIME ZONE,
    address          TEXT,
    phone            VARCHAR(20),
    email            VARCHAR(60),
    CONSTRAINT restaurant_pkey PRIMARY KEY (id)
);

CREATE TABLE restaurant_reviews
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    restaurant_id BIGINT,
    user_id       BIGINT,
    rating        numeric(3, 1),
    content       TEXT,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT restaurant_reviews_pkey PRIMARY KEY (id)
);

CREATE TABLE restaurant_tags
(
    restaurant_id BIGINT,
    tag_id        BIGINT
);

CREATE TABLE tables
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    capacity               INTEGER,
    restaurant_id          BIGINT,
    reservation_time_start TIMESTAMP WITHOUT TIME ZONE,
    reserved               BOOLEAN,
    reservation_time_end   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT tables_pkey PRIMARY KEY (id)
);

CREATE TABLE tags
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          TEXT,
    restaurant_id BIGINT,
    CONSTRAINT tags_pkey PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username             VARCHAR(50)                             NOT NULL,
    email                VARCHAR(100)                            NOT NULL,
    password             TEXT                                    NOT NULL,
    verification_code    TEXT,
    verification_expires TIMESTAMP WITHOUT TIME ZONE,
    enabled              BOOLEAN,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE tags
    ADD CONSTRAINT tags_name_key UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE dishes_ingredients
    ADD CONSTRAINT dishes_ingredients_dish_id_fkey FOREIGN KEY (dish_id) REFERENCES dishes (id) ON DELETE NO ACTION;

ALTER TABLE dishes_ingredients
    ADD CONSTRAINT dishes_ingredients_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES ingredients (id) ON DELETE NO ACTION;

ALTER TABLE dishes
    ADD CONSTRAINT dishes_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE NO ACTION;

ALTER TABLE reservations
    ADD CONSTRAINT reservations_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE NO ACTION;

ALTER TABLE reservations
    ADD CONSTRAINT reservations_table_id_fkey FOREIGN KEY (table_id) REFERENCES tables (id) ON DELETE NO ACTION;

ALTER TABLE reservations
    ADD CONSTRAINT reservations_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE restaurant_reviews
    ADD CONSTRAINT restaurant_reviews_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE NO ACTION;

ALTER TABLE restaurant_reviews
    ADD CONSTRAINT restaurant_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE restaurant_tags
    ADD CONSTRAINT restaurant_tags_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE NO ACTION;

ALTER TABLE restaurant_tags
    ADD CONSTRAINT restaurant_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE NO ACTION;

ALTER TABLE tables
    ADD CONSTRAINT tables_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE NO ACTION;

ALTER TABLE tags
    ADD CONSTRAINT tags_restaurant__fk FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE NO ACTION;