CREATE SEQUENCE IF NOT EXISTS dishes_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS ingredients_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS reservations_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS restaurant_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS restaurant_reviews_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS tables_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS tags_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS dishes
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    restaurant_id BIGINT,
    price         numeric(38, 2),
    CONSTRAINT dishes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS dishes_ingredients
(
    ingredient_id  BIGINT NOT NULL,
    dish_id        BIGINT NOT NULL,
    quantity       numeric(6, 2),
    ingredients_id BIGINT NOT NULL,
    CONSTRAINT dishes_ingredients_pkey PRIMARY KEY (ingredient_id, dish_id)
);

CREATE TABLE IF NOT EXISTS ingredients
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    quantity INTEGER,
    unit     VARCHAR(255),
    CONSTRAINT ingredients_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS reservations
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                BIGINT,
    table_id               BIGINT,
    restaurant_id          BIGINT,
    reservation_time_end   TIMESTAMP WITHOUT TIME ZONE,
    reservation_time_start TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT reservations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS restaurant
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255),
    description      VARCHAR(255),
    location         VARCHAR(255),
    rating           DOUBLE PRECISION,
    count_of_reviews INTEGER,
    address          VARCHAR(255),
    phone            VARCHAR(255),
    email            VARCHAR(255),
    work_time_closed TIMESTAMP WITHOUT TIME ZONE,
    work_time_open   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT restaurant_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS restaurant_reviews
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    restaurant_id BIGINT,
    user_id       BIGINT,
    rating        numeric(38, 2),
    content       VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT restaurant_reviews_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS restaurant_tags
(
    restaurant_id BIGINT,
    tag_id        BIGINT
);

CREATE TABLE IF NOT EXISTS restaurant_work_days
(
    restaurant_id BIGINT   NOT NULL,
    work_days     SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS tables
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    capacity               INTEGER,
    restaurant_id          BIGINT,
    reservation_time_start TIMESTAMP WITHOUT TIME ZONE,
    reserved               BOOLEAN,
    reservation_time_end   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT tables_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tags
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    restaurant_id BIGINT,
    CONSTRAINT tags_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_roles
(
    user_id BIGINT NOT NULL,
    roles   SMALLINT
);

CREATE TABLE IF NOT EXISTS users
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username             VARCHAR(255)                            NOT NULL,
    email                VARCHAR(255)                            NOT NULL,
    password             VARCHAR(255)                            NOT NULL,
    verification_code    INTEGER,
    verification_expires time WITHOUT TIME ZONE,
    enabled              BOOLEAN,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE tags
    ADD CONSTRAINT tags_name_key UNIQUE (name);

ALTER TABLE dishes_ingredients
    ADD CONSTRAINT ukmg9ai667s6qas9st4c9gwn76h UNIQUE (ingredients_id);

ALTER TABLE users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE dishes_ingredients
    ADD CONSTRAINT dishes_ingredients_dish_id_fkey FOREIGN KEY (dish_id) REFERENCES dishes (id) ON DELETE NO ACTION;

ALTER TABLE dishes_ingredients
    ADD CONSTRAINT dishes_ingredients_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES ingredients (id) ON DELETE NO ACTION;

ALTER TABLE dishes
    ADD CONSTRAINT dishes_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE NO ACTION;

ALTER TABLE restaurant_work_days
    ADD CONSTRAINT fk2m9w9j362b5uxau8ubtel5n46 FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE NO ACTION;

ALTER TABLE dishes_ingredients
    ADD CONSTRAINT fk8vwn8ia4upc5wyt7ilhquiua2 FOREIGN KEY (ingredients_id) REFERENCES ingredients (id) ON DELETE NO ACTION;

ALTER TABLE user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE reservations
    ADD CONSTRAINT reservations_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE NO ACTION;

ALTER TABLE reservations
    ADD CONSTRAINT reservations_table_id_fkey FOREIGN KEY (table_id) REFERENCES tables (id) ON DELETE NO ACTION;

ALTER TABLE reservations
    ADD CONSTRAINT reservations_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE restaurant_reviews
    ADD CONSTRAINT restaurant_reviews_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE NO ACTION;

ALTER TABLE restaurant_reviews
    ADD CONSTRAINT restaurant_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE restaurant_tags
    ADD CONSTRAINT restaurant_tags_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE NO ACTION;

ALTER TABLE restaurant_tags
    ADD CONSTRAINT restaurant_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE NO ACTION;

ALTER TABLE tables
    ADD CONSTRAINT tables_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE NO ACTION;

ALTER TABLE tags
    ADD CONSTRAINT tags_restaurant__fk FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE NO ACTION;